image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint

build:
  stage: build
  script:
    - npm install

lint&styles:
  stage: lint&styles
  script:
    - npm run lint
    - npm run lint:styles
